### ISSUE TITLE
Problem with hollow area

### ISSUE THREAD

**Issue by kuzyn1** [yvt/terravox#12]
I tried to load a classic bridgewars. I'm using Terravox-0.0.3-Windows.zip
![bez tytulu](https://cloud.githubusercontent.com/assets/4819951/20641955/80352ed6-b403-11e6-83cb-8dc049b22cb4.png)

**Comment by noway** [comment]
Terravox is a simple editor afaik and doesn't support hollow areas, so that's quite expected.

**Comment by kuzyn1** [comment]
So, is there any working editor?

**Comment by yvt** [comment]
Terravox is a map editor designed for rapid creation of height-map based terrain. While it's useful during the early stages of map creation, you'll need a more advanced editor for later stages or editing existing maps since it won't support hollow areas.

For serious editing, I would recommend a full-featured editor like `voxed.exe` that comes with AoS 0.75β original client.  It also appears that some people use specialized pyspades scripts for collaborative editing.

**Comment by noway** [comment]
or blockman2d, some people were talking about it

**Comment by kuzyn1** [comment]
@yvt 
@noway421 
So there is not any good editor out here. Your terravox doesnt support hollow area, blockman2d is just a generator and voxed.exe is archaic. Maybe that's one of the problems why AoS is not so popular ;)

btw respect for all mappers that worked on voxed ._.
